# Generated by Django 4.2.1 on 2024-05-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='slug',
        ),
    ]
