# Generated by Django 4.2.1 on 2024-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0002_remove_master_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['time_create']},
        ),
        migrations.AddField(
            model_name='master',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['time_create'], name='nails_maste_time_cr_fbd9dc_idx'),
        ),
    ]
