# Generated by Django 4.2.1 on 2024-05-15 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0006_service_delete_client_delete_worker_master_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.service'),
        ),
    ]
